services:
  - type: web
    name: data-egypt
    runtime: node
    plan: starter
    buildCommand: git lfs pull && npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"
      - key: NODE_ENV
        value: production
